-- ============================================================
-- Server Monitoring / Log Management Database
-- PostgreSQL 15+ with TimescaleDB 2.13+
--
-- Run MANUALLY. Spring Boot does not execute this file
-- (only schema.sql / data.sql at the classpath root are auto-run).
--
--   psql -U postgres -d mhub_db -f src/main/resources/database/init.sql
--
-- Every statement is idempotent; re-running is safe.
-- Hibernate must be ddl-auto=validate (never update) once this has run.
-- ============================================================


-- ============================================================
-- 0. TEARDOWN (uncomment for a clean rebuild -- DESTROYS DATA)
-- ============================================================

-- DROP TABLE IF EXISTS server_storage_summary CASCADE;
-- DROP TABLE IF EXISTS server_storage   CASCADE;
-- DROP TABLE IF EXISTS server_resources CASCADE;
-- DROP TABLE IF EXISTS server_logs      CASCADE;
-- DROP TABLE IF EXISTS servers          CASCADE;
-- DROP TABLE IF EXISTS systems          CASCADE;
-- DROP TABLE IF EXISTS users            CASCADE;


-- ============================================================
-- 1. EXTENSION + SESSION TIME ZONE
-- ============================================================

-- Requires superuser, and timescaledb in shared_preload_libraries.
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Every timestamp column in this schema is timestamptz -- absolute
-- instants, independent of where the database runs. This setting only
-- affects how psql renders them; the API renders in monitor.display-zone.
-- Takes effect on the NEXT connection.
ALTER DATABASE monitor_db SET timezone TO 'Asia/Phnom_Penh';


-- ============================================================
-- 2. SYSTEMS
-- ============================================================

CREATE TABLE IF NOT EXISTS systems (
    uuid        varchar(36)  NOT NULL,
    name        varchar(255) NOT NULL,
    created_at  timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT pk_systems      PRIMARY KEY (uuid),
    CONSTRAINT uk_systems_name UNIQUE (name)
);


-- ============================================================
-- 3. SERVERS
-- ============================================================

CREATE TABLE IF NOT EXISTS servers (
    uuid         varchar(36)  NOT NULL,
    system_id    varchar(36)  NOT NULL,
    name         varchar(255) NOT NULL,
    ip           varchar(45)  NOT NULL,
    server_type  varchar(20)  NOT NULL,
    -- Free-text note about the server. Nullable: existing servers predate
    -- it, and it is never required to register one.
    description  varchar(500),
    created_at   timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT pk_servers PRIMARY KEY (uuid),

    CONSTRAINT fk_servers_system
        FOREIGN KEY (system_id) REFERENCES systems (uuid)
        ON DELETE CASCADE,

    CONSTRAINT uk_servers_system_name UNIQUE (system_id, name),

    -- varchar + CHECK, NOT a native pg enum:
    -- @Enumerated(EnumType.STRING) maps to varchar, and a native
    -- enum type would make Hibernate's validate fail.
    CONSTRAINT ck_servers_server_type
        CHECK (server_type IN ('DATABASE', 'APP', 'WEB'))
);

CREATE INDEX IF NOT EXISTS idx_servers_system_id ON servers (system_id);
CREATE INDEX IF NOT EXISTS idx_servers_ip        ON servers (ip);
CREATE INDEX IF NOT EXISTS idx_servers_type      ON servers (server_type);


-- ============================================================
-- 4. USERS
--
-- Absent from the old servers.sql -- it existed only because
-- ddl-auto=update created it. Without this block, switching to
-- validate fails at startup and authentication dies with it.
--
-- id: GenerationType.IDENTITY. "BY DEFAULT" rather than "ALWAYS"
-- so explicit-id inserts (seed data, fixtures) still work.
-- Column names follow Boot's CamelCaseToUnderscoresNamingStrategy:
-- isAdmin -> is_admin, createdAt -> created_at.
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) NOT NULL,
    email       varchar(255) NOT NULL,
    password    varchar(255) NOT NULL,
    status      varchar(20)  NOT NULL,
    is_admin    boolean      NOT NULL,
    created_at  timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),

    CONSTRAINT ck_users_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED'))
);


-- ============================================================
-- 5. SERVER LOGS  (configuration, not time-series)
-- ============================================================

CREATE TABLE IF NOT EXISTS server_logs (
    uuid       varchar(36)  NOT NULL,
    server_id  varchar(36)  NOT NULL,
    channel    varchar(100) NOT NULL,
    pub_path   varchar(500) NOT NULL,
    save_path  varchar(500) NOT NULL,

    CONSTRAINT pk_server_logs PRIMARY KEY (uuid),

    CONSTRAINT fk_server_logs_server
        FOREIGN KEY (server_id) REFERENCES servers (uuid)
        ON DELETE CASCADE,

    CONSTRAINT uk_server_logs_channel UNIQUE (server_id, channel)
);

CREATE INDEX IF NOT EXISTS idx_server_logs_server_id ON server_logs (server_id);
CREATE INDEX IF NOT EXISTS idx_server_logs_channel   ON server_logs (channel);


-- ============================================================
-- 6. SERVER RESOURCES  (hypertable -- one row per scrape)
--
-- No surrogate uuid. Natural PK (server_id, record_timestamp):
--   * TimescaleDB requires the partition column in every unique index
--   * it is exactly the index the hot query wants
--     (WHERE server_id = ? ORDER BY record_timestamp DESC LIMIT n)
--   * duplicate Redis deliveries become free dedup via
--     INSERT ... ON CONFLICT DO NOTHING
--
-- No `channel` column: one row per scrape, not one per metric channel.
-- If an agent ever publishes several resource-* channels per server,
-- channel must join the PK -- prefer collapsing the agent instead.
--
-- Types chosen for compression and honesty:
--   real    for percentages (never double precision for a 0-100 value)
--   bigint  for byte counts (bytes, not MB -- no unit ambiguity)
--   numeric is deliberately avoided: slower, compresses poorly
--
-- All metric columns are nullable so a partial payload still writes.
-- No CHECK constraints on metrics on purpose: one bad value from an
-- agent would abort the whole batch insert.
--
-- Columns mirror the observed resource-info payload, one column per
-- leaf field (the payload nests under cpu/memory/swap/network):
--
--   {"serverId","timestamp","uptimeSeconds",
--    "cpu":{"count","usedPercent","load1","load5","load15"},
--    "memory":{"totalBytes","usedBytes","availableBytes","usedPercent","estimated"},
--    "swap":{"totalBytes","usedBytes","usedPercent"},
--    "network":{"rxBytesPerSec","txBytesPerSec"}}
--
-- usedPercent is stored rather than derived: the agent reports
-- memory.estimated, so its percentage carries estimation semantics we
-- cannot faithfully recompute from the byte counts.
--
-- The agent sends no CPU breakdown (user/system/iowait), no disk I/O and
-- no process count, so those columns are omitted rather than left
-- permanently NULL. Re-adding one is an ALTER plus an entity field.
-- ============================================================

CREATE TABLE IF NOT EXISTS server_resources (
    server_id            varchar(36)  NOT NULL,
    record_timestamp     timestamptz  NOT NULL,

    -- Host          <- uptimeSeconds
    uptime_seconds       bigint,

    -- CPU           <- cpu.*
    cpu_count            smallint,
    cpu_usage_pct        real,
    load_avg_1m          real,
    load_avg_5m          real,
    load_avg_15m         real,

    -- Memory        <- memory.*
    mem_total_bytes      bigint,
    mem_used_bytes       bigint,
    mem_available_bytes  bigint,
    mem_used_pct         real,
    mem_estimated        boolean,

    -- Swap          <- swap.*
    swap_total_bytes     bigint,
    swap_used_bytes      bigint,
    swap_used_pct        real,

    -- Network       <- network.*
    -- The agent sends these as fractional doubles (e.g. 103669.046).
    -- bigint with rounding at ingest: sub-byte-per-second precision is
    -- meaningless, and integers aggregate without float drift.
    net_rx_bps           bigint,
    net_tx_bps           bigint,

    -- Escape hatch: unmapped agent fields land here instead of being
    -- lost, so a new metric is not a schema migration.
    extra                jsonb,

    CONSTRAINT pk_server_resources PRIMARY KEY (server_id, record_timestamp),

    CONSTRAINT fk_server_resources_server
        FOREIGN KEY (server_id) REFERENCES servers (uuid)
        ON DELETE CASCADE
);


-- ============================================================
-- 7. SERVER STORAGE  (hypertable -- one row per filesystem per scrape)
--
-- Published hourly on the storage- channel. One message carries a host
-- rollup plus an array of mounts, so a message fans out to N rows here
-- plus one row in server_storage_summary (section 7b).
--
--   {"serverId","timestamp",
--    "server":{"totalBytes","usedBytes","freeBytes","reservedBytes",
--              "usedPercent","partial"},
--    "mounts":[{"path","device","fsType","totalBytes","usedBytes",
--               "freeBytes","reservedBytes","usedPercent"},
--              {"path","fsType","error"}]}
--
-- Grain is per-mount, so mount_point (from mounts[].path) joins the PK.
--
-- free_bytes, not available_bytes: the agent reports freeBytes and
-- reservedBytes separately, and on Unix "free" and "available" differ by
-- exactly those reserved blocks. Naming the column after the agent's own
-- field avoids implying a conversion we do not perform.
--
-- used_pct is stored, not derived. The agent computes
-- used/(used+free) -- reserved blocks excluded from the denominator --
-- which is not the obvious used/total. For the sample mount those give
-- 25.70% and 24.41% respectively; deriving it would silently disagree
-- with whatever the agent itself reports.
--
-- error is set when a mount could not be measured (unsupported
-- filesystem, missing path). Such a mount arrives with no metrics and
-- possibly no device or fsType, but is still stored on purpose: "the NAS
-- mount has been unreadable for six hours" is a monitoring signal, not
-- an absence of data. Hence every metric column stays nullable.
--
-- No inode columns: the agent does not report them.
-- ============================================================

CREATE TABLE IF NOT EXISTS server_storage (
    server_id         varchar(36)  NOT NULL,
    mount_point       varchar(255) NOT NULL,
    record_timestamp  timestamptz  NOT NULL,

    device            varchar(255),
    fstype            varchar(50),

    total_bytes       bigint,
    used_bytes        bigint,
    free_bytes        bigint,
    reserved_bytes    bigint,
    used_pct          real,

    -- NULL means the mount was measured successfully.
    error             varchar(500),

    -- Populated here, unlike server_resources: at an hourly cadence the
    -- storage cost is trivial, and keeping the raw mount object means no
    -- unmapped agent field is ever silently lost.
    extra             jsonb,

    CONSTRAINT pk_server_storage
        PRIMARY KEY (server_id, mount_point, record_timestamp),

    CONSTRAINT fk_server_storage_server
        FOREIGN KEY (server_id) REFERENCES servers (uuid)
        ON DELETE CASCADE
);


-- ============================================================
-- 7b. SERVER STORAGE SUMMARY  (hypertable -- host rollup per scrape)
--
-- The payload's "server" object. A separate table because the grain
-- differs: one row per server per scrape, not per mount.
--
-- The byte columns are verifiably the sum of the non-error mounts, so
-- they could be derived with SUM(). `partial` could not -- it is a
-- per-scrape fact about whether the rollup covered everything, and no
-- aggregate over the mount rows can reconstruct it. That single column
-- is what makes this a table rather than a view.
-- ============================================================

CREATE TABLE IF NOT EXISTS server_storage_summary (
    server_id         varchar(36)  NOT NULL,
    record_timestamp  timestamptz  NOT NULL,

    total_bytes       bigint,
    used_bytes        bigint,
    free_bytes        bigint,
    reserved_bytes    bigint,
    used_pct          real,
    partial           boolean,

    extra             jsonb,

    CONSTRAINT pk_server_storage_summary
        PRIMARY KEY (server_id, record_timestamp),

    CONSTRAINT fk_server_storage_summary_server
        FOREIGN KEY (server_id) REFERENCES servers (uuid)
        ON DELETE CASCADE
);


-- ============================================================
-- 8. HYPERTABLES
--
-- Chunk interval is sized against each table's retention window, never
-- left at the 7-day default. Two failure modes to stay between:
--
--   chunks too LARGE  -- if one chunk spans the whole retention window,
--                        drop_chunks can never drop anything
--   chunks too SMALL  -- every chunk is a real table with its own
--                        indexes, so hundreds of near-empty chunks cost
--                        far more in metadata than the rows are worth
--
--   server_resources        3-5s scrape,  1-day retention  -> 1 hour
--                           ~24 chunks, ~17k rows each
--   server_storage(_summary) hourly scrape, 30-day retention -> 1 day
--                           ~30 chunks, ~480 / ~120 rows each
--
-- At 1-hour chunks the 30-day storage tables would need 720 chunks
-- holding ~20 rows apiece -- all overhead, no benefit.
--
-- A foreign key FROM a hypertable TO a regular table is supported
-- (only the reverse direction is rejected), and drop_chunks still
-- works with it in place.
-- ============================================================

SELECT create_hypertable(
    'server_resources',
    by_range('record_timestamp', INTERVAL '1 hour'),
    if_not_exists => TRUE
);

SELECT create_hypertable(
    'server_storage',
    by_range('record_timestamp', INTERVAL '1 day'),
    if_not_exists => TRUE
);

SELECT create_hypertable(
    'server_storage_summary',
    by_range('record_timestamp', INTERVAL '1 day'),
    if_not_exists => TRUE
);

-- create_hypertable(if_not_exists => TRUE) does NOT change the interval
-- of a hypertable that already exists, so re-running this file would
-- silently leave an old value in place. These make the file corrective
-- as well as idempotent. They affect future chunks only; existing
-- chunks keep the interval they were created with.
SELECT set_chunk_time_interval('server_resources',       INTERVAL '1 hour');
SELECT set_chunk_time_interval('server_storage',         INTERVAL '1 day');
SELECT set_chunk_time_interval('server_storage_summary', INTERVAL '1 day');

-- TimescaleDB < 2.13 does not have by_range(); use this form instead:
--
-- SELECT create_hypertable('server_resources', 'record_timestamp',
--     chunk_time_interval => INTERVAL '1 hour', if_not_exists => TRUE);
-- SELECT create_hypertable('server_storage', 'record_timestamp',
--     chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);
-- SELECT create_hypertable('server_storage_summary', 'record_timestamp',
--     chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);


-- ============================================================
-- 9. RETENTION
--
--   server_resources         1 day   -- 3-5s scrapes; volume is the constraint
--   server_storage           30 days -- hourly scrapes; capacity trending
--   server_storage_summary   30 days
--
-- drop_chunks is a metadata operation, so this costs nothing compared
-- to a nightly DELETE churning dead tuples.
--
-- Removed and re-added rather than add(if_not_exists => TRUE), because
-- that form leaves an EXISTING policy untouched -- re-running this file
-- would not apply a changed interval. Remove-then-add makes the value
-- declared here authoritative.
--
-- Compression is still NOT enabled. Even at 30 days the storage tables
-- hold on the order of 14k rows; columnar compression is worth its
-- complexity at a far larger scale, or alongside continuous aggregates
-- retained longer than the raw data.
-- ============================================================

SELECT remove_retention_policy('server_resources',       if_exists => TRUE);
SELECT remove_retention_policy('server_storage',         if_exists => TRUE);
SELECT remove_retention_policy('server_storage_summary', if_exists => TRUE);

SELECT add_retention_policy('server_resources',       INTERVAL '1 day');
SELECT add_retention_policy('server_storage',         INTERVAL '30 days');
SELECT add_retention_policy('server_storage_summary', INTERVAL '30 days');


-- ============================================================
-- VERIFY (run these after the script)
-- ============================================================

-- \d server_resources
-- SELECT hypertable_name, num_dimensions FROM timescaledb_information.hypertables;
-- SELECT hypertable_name, config FROM timescaledb_information.jobs
--   WHERE proc_name = 'policy_retention';
-- SELECT table_name FROM information_schema.tables
--   WHERE table_schema = 'public' ORDER BY table_name;

-- ============================================================
-- END
-- ============================================================
