package com.dev.monitor.services;

import com.dev.monitor.dto.server.ServerLogCreateRequest;
import com.dev.monitor.dto.server.ServerLogResponse;
import com.dev.monitor.entity.server.Server;
import com.dev.monitor.entity.server.ServerLog;
import com.dev.monitor.entity.server.ServerType;
import com.dev.monitor.entity.system.SystemEntity;
import com.dev.monitor.exception.server.ServerLogAlreadyExistsException;
import com.dev.monitor.exception.server.ServerNotFoundException;
import com.dev.monitor.repository.server.ServerLogRepository;
import com.dev.monitor.repository.server.ServerRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ServerLogServiceTest {

    @Mock
    private ServerLogRepository serverLogRepository;

    @Mock
    private ServerRepository serverRepository;

    @InjectMocks
    private ServerLogService serverLogService;

    private SystemEntity system;
    private Server server;

    @BeforeEach
    void setUp() {
        system = new SystemEntity("ecustoms");
        system.setUuid("sys-01");

        server = new Server(system, "ecustoms-Oracle-Dev", "10.0.9.16", ServerType.DATABASE);
        server.setUuid("srv-01");
    }

    @Test
    void shouldCreateServerLogWithAutoGeneratedSavePathByServerName() {
        when(serverRepository.findById("ecustoms-Oracle-Dev")).thenReturn(Optional.empty());
        when(serverRepository.findByName("ecustoms-Oracle-Dev")).thenReturn(List.of(server));
        when(serverLogRepository.existsByServerUuidAndChannel("srv-01", "log-listener")).thenReturn(false);

        ServerLog savedEntity = new ServerLog(server, "log-listener", "/var/log/listener.log", "logs/ecustoms-Oracle-Dev/log-listener");
        savedEntity.setUuid("log-01");
        when(serverLogRepository.save(any(ServerLog.class))).thenReturn(savedEntity);

        ServerLogCreateRequest request = new ServerLogCreateRequest("ecustoms-Oracle-Dev", "log-listener", "/var/log/listener.log");
        ServerLogResponse response = serverLogService.createServerLog(request);

        assertNotNull(response);
        assertEquals("log-01", response.uuid());
        assertEquals("srv-01", response.serverId());
        assertEquals("ecustoms-Oracle-Dev", response.serverName());
        assertEquals("log-listener", response.channel());
        assertEquals("/var/log/listener.log", response.pubPath());
        assertEquals("logs/ecustoms-Oracle-Dev/log-listener", response.savePath());

        ArgumentCaptor<ServerLog> captor = ArgumentCaptor.forClass(ServerLog.class);
        verify(serverLogRepository).save(captor.capture());
        assertEquals("logs/ecustoms-Oracle-Dev/log-listener", captor.getValue().getSavePath());
    }

    @Test
    void shouldCreateServerLogWithServerUuid() {
        when(serverRepository.findById("srv-01")).thenReturn(Optional.of(server));
        when(serverLogRepository.existsByServerUuidAndChannel("srv-01", "log-listener")).thenReturn(false);

        ServerLog savedEntity = new ServerLog(server, "log-listener", "/var/log/listener.log", "logs/ecustoms-Oracle-Dev/log-listener");
        savedEntity.setUuid("log-01");
        when(serverLogRepository.save(any(ServerLog.class))).thenReturn(savedEntity);

        ServerLogCreateRequest request = new ServerLogCreateRequest("srv-01", "log-listener", "/var/log/listener.log");
        ServerLogResponse response = serverLogService.createServerLog(request);

        assertNotNull(response);
        assertEquals("log-01", response.uuid());
        assertEquals("srv-01", response.serverId());
    }

    @Test
    void shouldThrowExceptionWhenServerNotFoundOnCreate() {
        when(serverRepository.findById("unknown-srv")).thenReturn(Optional.empty());
        when(serverRepository.findByName("unknown-srv")).thenReturn(List.of());

        ServerLogCreateRequest request = new ServerLogCreateRequest("unknown-srv", "log-listener", "/var/log/listener.log");

        assertThrows(ServerNotFoundException.class, () -> serverLogService.createServerLog(request));
    }

    @Test
    void shouldThrowExceptionWhenChannelAlreadyExistsForServer() {
        when(serverRepository.findById("srv-01")).thenReturn(Optional.of(server));
        when(serverLogRepository.existsByServerUuidAndChannel("srv-01", "log-listener")).thenReturn(true);

        ServerLogCreateRequest request = new ServerLogCreateRequest("srv-01", "log-listener", "/var/log/listener.log");

        assertThrows(ServerLogAlreadyExistsException.class, () -> serverLogService.createServerLog(request));
    }

    @Test
    void shouldGetLogsByServerName() {
        when(serverRepository.findById("ecustoms-Oracle-Dev")).thenReturn(Optional.empty());
        when(serverRepository.findByName("ecustoms-Oracle-Dev")).thenReturn(List.of(server));

        ServerLog log1 = new ServerLog(server, "log-listener", "/var/log/listener.log", "logs/ecustoms-Oracle-Dev/log-listener");
        log1.setUuid("log-01");
        when(serverLogRepository.findByServerUuid("srv-01")).thenReturn(List.of(log1));

        List<ServerLogResponse> result = serverLogService.getLogs("ecustoms-Oracle-Dev");

        assertEquals(1, result.size());
        assertEquals("log-01", result.get(0).uuid());
        assertEquals("srv-01", result.get(0).serverId());
        assertEquals("ecustoms-Oracle-Dev", result.get(0).serverName());
        assertEquals("log-listener", result.get(0).channel());
    }

    @Test
    void shouldGetLogsByServerUuid() {
        when(serverRepository.findById("srv-01")).thenReturn(Optional.of(server));

        ServerLog log1 = new ServerLog(server, "log-listener", "/var/log/listener.log", "logs/ecustoms-Oracle-Dev/log-listener");
        log1.setUuid("log-01");
        when(serverLogRepository.findByServerUuid("srv-01")).thenReturn(List.of(log1));

        List<ServerLogResponse> result = serverLogService.getLogs("srv-01");

        assertEquals(1, result.size());
        assertEquals("log-01", result.get(0).uuid());
    }

    @Test
    void shouldReturnEmptyListWhenServerHasNoLogs() {
        when(serverRepository.findById("srv-01")).thenReturn(Optional.of(server));
        when(serverLogRepository.findByServerUuid("srv-01")).thenReturn(List.of());

        List<ServerLogResponse> result = serverLogService.getLogs("srv-01");

        assertNotNull(result);
        assertTrue(result.isEmpty());
    }

    @Test
    void shouldThrowExceptionWhenServerNotFoundOnGet() {
        when(serverRepository.findById("unknown-srv")).thenReturn(Optional.empty());
        when(serverRepository.findByName("unknown-srv")).thenReturn(List.of());

        assertThrows(ServerNotFoundException.class, () -> serverLogService.getLogs("unknown-srv"));
    }

    @Test
    void shouldGetAllLogsWhenNoIdentifierProvided() {
        ServerLog log1 = new ServerLog(server, "log-listener", "/var/log/listener.log", "logs/ecustoms-Oracle-Dev/log-listener");
        log1.setUuid("log-01");
        when(serverLogRepository.findAllWithServer()).thenReturn(List.of(log1));

        List<ServerLogResponse> result = serverLogService.getLogs(null);

        assertEquals(1, result.size());
        assertEquals("log-01", result.get(0).uuid());
    }
}
